// AUTO-GENERATED by scripts/generate-plugin-registry.ts — do not edit

export interface PluginContentEntry {
  name: string;
  version: string;
  description?: string;
  icon?: string;
  actionType?: string;
  authRequired?: boolean;
  capabilities: string[];
  artifacts: Array<{ type: string; filename: string; content: string; sortOrder: number }>;
}

export const pluginContentRegistry: PluginContentEntry[] = [
  {
    name: "1password",
    version: "0.0.1",
    description: "Secret management for agent sessions",
    icon: "🔑",
    capabilities: [],
    artifacts: [],
  },
  {
    name: "browser",
    version: "0.0.1",
    description: "Browser control via agent-browser CLI",
    icon: "🌐",
    capabilities: ["skills"],
    artifacts: [
      { type: "skill", filename: "browser.md", content: `---
name: browser
description: Control the Chromium browser using the agent-browser CLI. Navigate, click, type, fill forms, take snapshots, extract content, and more.
---

# Browser Control via agent-browser CLI

You have \`agent-browser\` installed globally. It controls a real Chromium browser on display \`:99\` (visible in the user's VNC panel).

**Always use \`--headed\` flag** so the browser renders on the VNC display:

\`\`\`bash
agent-browser --headed <command>
\`\`\`

## Core Workflow

1. **Open a URL**: \`agent-browser --headed open <url>\`
2. **Take a snapshot** to see page structure: \`agent-browser --headed snapshot -i -c\`
3. **Interact** using element refs from the snapshot: \`agent-browser --headed click @e3\`
4. **Verify visually**: Use the \`browser_screenshot\` tool to capture the VNC display and show it in chat.

## Navigation

\`\`\`bash
agent-browser --headed open <url>          # Navigate to URL
agent-browser --headed back                # Go back
agent-browser --headed forward             # Go forward
agent-browser --headed reload              # Reload page
agent-browser --headed close               # Close browser
\`\`\`

## Clicking & Focus

\`\`\`bash
agent-browser --headed click <selector>    # Click element (CSS selector or @ref)
agent-browser --headed dblclick <selector> # Double-click
agent-browser --headed focus <selector>    # Focus element
agent-browser --headed hover <selector>    # Hover over element
\`\`\`

## Text Input

\`\`\`bash
agent-browser --headed type <selector> <text>   # Type into element (appends)
agent-browser --headed fill <selector> <text>    # Clear field and fill with text
agent-browser --headed press <key>               # Press key (Enter, Tab, Control+a, etc.)
\`\`\`

## Form Controls

\`\`\`bash
agent-browser --headed select <selector> <value> # Select dropdown option
agent-browser --headed check <selector>           # Check checkbox
agent-browser --headed uncheck <selector>         # Uncheck checkbox
agent-browser --headed upload <selector> <files>  # Upload files
\`\`\`

## Scrolling

\`\`\`bash
agent-browser --headed scroll down [px]           # Scroll down (default ~page)
agent-browser --headed scroll up [px]             # Scroll up
agent-browser --headed scrollintoview <selector>  # Scroll element into view
\`\`\`

## Snapshots (Accessibility Tree)

Snapshots give you a structured view of the page with element refs (\`@e1\`, \`@e2\`, etc.) you can use in subsequent commands.

\`\`\`bash
agent-browser --headed snapshot              # Full accessibility tree
agent-browser --headed snapshot -i           # Interactive elements only
agent-browser --headed snapshot -c           # Compact output
agent-browser --headed snapshot -i -c        # Interactive + compact (recommended)
agent-browser --headed snapshot -d 3         # Limit depth to 3
agent-browser --headed snapshot -s "main"    # Scope to a CSS selector
\`\`\`

After a snapshot, use the \`@ref\` identifiers to interact:

\`\`\`bash
agent-browser --headed click @e3
agent-browser --headed fill @e7 "search query"
\`\`\`

## Getting Page Information

\`\`\`bash
agent-browser --headed get title             # Page title
agent-browser --headed get url               # Current URL
agent-browser --headed get text <selector>   # Text content of element
agent-browser --headed get html <selector>   # innerHTML of element
agent-browser --headed get value <selector>  # Input value
agent-browser --headed get attr <sel> <attr> # Element attribute
agent-browser --headed get count <selector>  # Count matching elements
\`\`\`

## Checking Element State

\`\`\`bash
agent-browser --headed is visible <selector>  # Check visibility
agent-browser --headed is enabled <selector>  # Check if enabled
agent-browser --headed is checked <selector>  # Check if checked
\`\`\`

## Waiting

\`\`\`bash
agent-browser --headed wait <selector>         # Wait for element to appear
agent-browser --headed wait 2000               # Wait 2 seconds
agent-browser --headed wait --text "Success"   # Wait for text to appear
agent-browser --headed wait --url "**/dashboard" # Wait for URL pattern
\`\`\`

**NEVER use \`wait --load networkidle\`** — many sites never reach network idle (analytics, websockets, polling). It will hang indefinitely and can break the session.

## Semantic Finding

Find elements by role, text, label, etc. and perform actions:

\`\`\`bash
agent-browser --headed find role button click              # Click first button
agent-browser --headed find text "Submit" click            # Click element with text
agent-browser --headed find label "Email" fill "a@b.com"   # Fill by label
agent-browser --headed find placeholder "Search" fill "q"  # Fill by placeholder
agent-browser --headed find testid "login-btn" click       # Click by data-testid
\`\`\`

## Tabs

\`\`\`bash
agent-browser --headed tab                   # List open tabs
agent-browser --headed tab new [url]         # Open new tab
agent-browser --headed tab 2                 # Switch to tab 2
agent-browser --headed tab close [n]         # Close tab
\`\`\`

## JavaScript Evaluation

\`\`\`bash
agent-browser --headed eval "document.title"
agent-browser --headed eval "window.scrollTo(0, document.body.scrollHeight)"
\`\`\`

## Dialogs

\`\`\`bash
agent-browser --headed dialog accept [text]  # Accept alert/confirm/prompt
agent-browser --headed dialog dismiss        # Dismiss dialog
\`\`\`

## Cookies & Storage

\`\`\`bash
agent-browser --headed cookies               # List cookies
agent-browser --headed cookies clear         # Clear cookies
agent-browser --headed storage local         # List localStorage
agent-browser --headed storage local <key>   # Get specific key
\`\`\`

## Common Workflow Examples

### Navigate and extract content

\`\`\`bash
timeout 15 agent-browser --headed open "https://example.com"
agent-browser --headed snapshot -i -c
agent-browser --headed get title
\`\`\`

### Fill a form

\`\`\`bash
timeout 15 agent-browser --headed open "https://example.com/login"
agent-browser --headed snapshot -i -c
timeout 10 agent-browser --headed fill @e3 "user@example.com"
timeout 10 agent-browser --headed fill @e5 "password123"
timeout 15 agent-browser --headed click @e7
agent-browser --headed wait 2000
agent-browser --headed snapshot -i -c
\`\`\`

### Using snapshot refs

\`\`\`bash
agent-browser --headed open "https://news.ycombinator.com"
agent-browser --headed snapshot -i -c
# Output shows refs like @e1, @e2, @e3...
agent-browser --headed click @e5    # Click the 5th interactive element
agent-browser --headed get title    # Verify navigation
\`\`\`

## Avoiding Hangs

Browser commands can hang if a page never finishes loading or a click triggers an unexpected navigation. **Always wrap browser commands with \`timeout\`** to prevent blocking the session:

\`\`\`bash
timeout 15 agent-browser --headed click @e3
timeout 15 agent-browser --headed open "https://example.com"
timeout 15 agent-browser --headed fill @e7 "text"
\`\`\`

Use \`timeout 15\` (15 seconds) as a sensible default. If a command times out, take a snapshot to see what happened and adjust your approach.

**Never use \`wait --load networkidle\`** — it hangs on most real-world sites. Instead, wait for specific elements:

\`\`\`bash
timeout 10 agent-browser --headed wait "input[name=email]"  # Wait for a specific element
timeout 10 agent-browser --headed wait --text "Welcome"     # Wait for specific text
\`\`\`

## Tips

- **Always take a screenshot** with \`browser_screenshot\` after navigating or clicking so you and the user can see the result.
- Use \`snapshot -i -c\` as your go-to for understanding page structure.
- Prefer \`fill\` over \`type\` for form fields (it clears first).
- The browser persists between commands within a session. No need to reopen it.
- If the browser isn't running, \`agent-browser --headed open <url>\` will start it.
`, sortOrder: 0 },
    ],
  },
  {
    name: "cloudflare",
    version: "0.0.1",
    description: "Cloudflare integration for DNS, zones, and workers",
    icon: "☁️",
    actionType: "mcp",
    capabilities: ["actions"],
    artifacts: [],
  },
  {
    name: "deepwiki",
    version: "0.0.1",
    description: "DeepWiki integration for repository knowledge base",
    icon: "📚",
    authRequired: false,
    capabilities: ["actions"],
    artifacts: [],
  },
  {
    name: "email-auth",
    version: "0.1.0",
    description: "Email/password identity provider",
    icon: "key",
    capabilities: [],
    artifacts: [],
  },
  {
    name: "github",
    version: "0.0.1",
    description: "GitHub integration for PRs, issues, repos, and webhooks",
    icon: "🐙",
    capabilities: ["actions","skills"],
    artifacts: [
      { type: "skill", filename: "github.md", content: `---
name: github
description: How to use GitHub integration tools — list repos, create PRs, manage issues, read files. Covers token model, available actions, attribution behavior, and common patterns.
---

# GitHub Integration Tools

You interact with GitHub through integration actions, NOT the \`gh\` CLI (which is not available in sandboxes).

## Quick Start

\`\`\`
list_tools service=github    # Discover available GitHub actions
call_tool github:github.<action_id> params={...} summary="..."
\`\`\`

## Token Model

GitHub actions use a single token resolved automatically:

- **User token (primary)** — personal OAuth token linked on the integrations page. Access to the user's own repos (public + private).
- **Bot token (fallback)** — org GitHub App installation token. Access to repos in organizations where the App is installed. Used when the user has no personal token or the action targets an org repo covered by the App.

The system resolves the best available token for each request. You do not pass a \`source\` parameter — credential routing is handled automatically based on the \`owner\` of the target repo.

**Anonymous access:** If configured by an admin, unauthenticated access to public repos may be available.

## Attribution

When acting under a bot token (App install), actions automatically add attribution so the user's identity is visible:

- **Commits** — \`Co-Authored-By: <name> <email>\` trailer appended to commit message
- **PR and issue bodies** — a suffix noting the action was performed on behalf of the user

Users connect their personal GitHub account at **Settings → Integrations → GitHub**.

## Available Actions

### Repository
- \`github.list_repos\` — list repositories accessible via the resolved token
- \`github.get_repository\` — get repo details by owner/name
- \`github.create_repository\` — create a new repository
- \`github.fork_repository\` — fork a repository
- \`github.read_repo_file\` — read a file from a repository

### Issues
- \`github.list_issues\` — list issues for a repo
- \`github.get_issue\` — get a specific issue by number
- \`github.create_issue\` — create a new issue
- \`github.update_issue\` — update an issue (title, body, state, labels)

### Pull Requests
- \`github.list_pull_requests\` — list PRs for a repo
- \`github.get_pull_request\` — get a specific PR by number
- \`github.inspect_pull_request\` — get detailed PR info (files, comments, check runs)
- \`github.create_pull_request\` — create a new PR
- \`github.update_pull_request\` — update a PR (title, body, state, labels)
- \`github.merge_pull_request\` — merge a PR
- \`github.create_comment\` — comment on an issue or PR

### Branches & Commits
- \`github.create_branch\` — create a branch from a ref
- \`github.delete_branch\` — delete a branch
- \`github.list_commits\` — list commits on a branch

### Search
- \`github.search_code\` — search code across repositories
- \`github.search_issues\` — search issues and PRs

### Releases & CI
- \`github.create_release\` — create a release with tag
- \`github.list_workflow_runs\` — list GitHub Actions workflow runs

## Common Patterns

### Create a PR after committing changes
\`\`\`
# Use git CLI for local operations
git checkout -b feature/my-change
# ... make changes, commit ...
git push -u origin feature/my-change

# Use integration tool for PR creation (not gh CLI)
call_tool github:github.create_pull_request \\
  owner=<owner> repo=<repo> \\
  title="My change" body="Description" \\
  head="feature/my-change" base="main" \\
  summary="Create PR for feature/my-change"
\`\`\`

### List all repos you have access to
\`\`\`
call_tool github:github.list_repos summary="List accessible repos"
\`\`\`

### Read a file without cloning
\`\`\`
call_tool github:github.read_repo_file \\
  owner=<owner> repo=<repo> path="README.md" \\
  summary="Read README from owner/repo"
\`\`\`

## Important Notes

- The \`gh\` CLI is NOT available. Always use \`call_tool\` with GitHub actions.
- Use git CLI for local operations (checkout, add, commit, push, pull).
- Use \`report_git_state\` after checking out branches or making commits.
- The \`summary\` parameter on \`call_tool\` is required for medium/high risk actions (like creating PRs). Make it descriptive.
- If a GitHub action fails with an auth error, the user may need to connect their account at Settings → Integrations → GitHub.
`, sortOrder: 0 },
    ],
  },
  {
    name: "gmail",
    version: "0.0.1",
    description: "Gmail integration for reading and sending emails",
    icon: "📧",
    capabilities: ["actions"],
    artifacts: [],
  },
  {
    name: "google-auth",
    version: "0.1.0",
    description: "Google OAuth identity provider",
    icon: "google",
    capabilities: [],
    artifacts: [],
  },
  {
    name: "google-calendar",
    version: "0.0.1",
    description: "Google Calendar integration for events and scheduling",
    icon: "📅",
    capabilities: ["actions","skills"],
    artifacts: [
      { type: "skill", filename: "google-calendar.md", content: `---
name: google-calendar
description: How to use Google Calendar tools effectively — managing events, checking availability, scheduling, and working with multiple calendars.
---

# Google Calendar

You have full access to Google Calendar through the \`google-calendar\` plugin.

## Available Tools

### Reading

- **\`calendar.list_calendars\`** — List all calendars the user has access to (with IDs, names, and access roles).
- **\`calendar.get_calendar\`** — Get details for a specific calendar.
- **\`calendar.list_events\`** — List events in a time range. Supports filtering by calendar, time bounds, search text, and single events expansion.
- **\`calendar.get_event\`** — Get full details of a specific event.

### Scheduling

- **\`calendar.create_event\`** — Create an event with title, times, attendees, location, description, and recurrence.
- **\`calendar.update_event\`** — Update any field of an existing event.
- **\`calendar.delete_event\`** — Delete an event.
- **\`calendar.quick_add\`** — Create an event from natural language (e.g., "Lunch with Alice tomorrow at noon").

### Availability

- **\`calendar.respond_to_event\`** — Accept, decline, or tentatively accept an event invitation.
- **\`calendar.query_free_busy\`** — Check busy/free status for one or more people over a time range.
- **\`calendar.find_available_slots\`** — Find open time slots when all specified attendees are available.

## Common Patterns

### Checking Today's Schedule

\`\`\`
calendar.list_events({
  calendarId: "primary",
  timeMin: "2026-03-15T00:00:00Z",
  timeMax: "2026-03-16T00:00:00Z",
  singleEvents: true,
  orderBy: "startTime"
})
\`\`\`

Always use \`singleEvents: true\` and \`orderBy: "startTime"\` when listing a day's events — this expands recurring events and sorts chronologically.

### Scheduling a Meeting

\`\`\`
calendar.create_event({
  calendarId: "primary",
  summary: "Architecture Review",
  start: "2026-03-20T14:00:00-07:00",
  end: "2026-03-20T15:00:00-07:00",
  attendees: ["alice@example.com", "bob@example.com"],
  description: "Review the new API design",
  location: "Conference Room B"
})
\`\`\`

### Finding a Time That Works

Use \`find_available_slots\` to find open times for a group:

\`\`\`
calendar.find_available_slots({
  attendees: ["alice@example.com", "bob@example.com"],
  timeMin: "2026-03-17T09:00:00-07:00",
  timeMax: "2026-03-21T17:00:00-07:00",
  durationMinutes: 30,
  maxResults: 5
})
\`\`\`

### Quick Event Creation

For simple events, \`quick_add\` parses natural language:

\`\`\`
calendar.quick_add({
  calendarId: "primary",
  text: "Team standup every weekday at 9:30am"
})
\`\`\`

### Recurring Events

Use RFC 5545 RRULE format for recurrence:

\`\`\`
calendar.create_event({
  calendarId: "primary",
  summary: "Weekly Sync",
  start: "2026-03-16T10:00:00-07:00",
  end: "2026-03-16T10:30:00-07:00",
  recurrence: ["RRULE:FREQ=WEEKLY;BYDAY=MO;COUNT=12"]
})
\`\`\`

Common RRULE patterns:
- \`RRULE:FREQ=DAILY\` — every day
- \`RRULE:FREQ=WEEKLY;BYDAY=MO,WE,FR\` — Mon/Wed/Fri
- \`RRULE:FREQ=MONTHLY;BYMONTHDAY=1\` — first of each month
- \`RRULE:FREQ=WEEKLY;COUNT=10\` — weekly for 10 occurrences
- \`RRULE:FREQ=WEEKLY;UNTIL=20261231T000000Z\` — weekly until end of year

### All-Day Events

Use date strings (no time component) for all-day events:

\`\`\`
calendar.create_event({
  calendarId: "primary",
  summary: "Company Holiday",
  start: "2026-03-20",
  end: "2026-03-21"
})
\`\`\`

Note: the end date is exclusive — a single all-day event on March 20 uses \`end: "2026-03-21"\`.

## Tips

- **Calendar ID**: Use \`"primary"\` for the user's main calendar. Use \`list_calendars\` to discover other calendar IDs.
- **Timezones**: Always include timezone offsets in datetime strings (e.g., \`-07:00\`). The user's local timezone is preferred.
- **Single events**: When listing, set \`singleEvents: true\` to expand recurring events into individual instances. Without this, you get the recurring event template, not the individual occurrences.
- **Attendees**: Pass email addresses as strings. The API handles sending invitations.
- **Updates**: Only pass the fields you want to change to \`update_event\`. Omitted fields are preserved.
`, sortOrder: 0 },
    ],
  },
  {
    name: "google-workspace",
    version: "0.0.1",
    description: "Google Workspace integration — Drive, Docs, and Sheets with unified OAuth and labels-based access guard",
    icon: "🏢",
    capabilities: ["actions","skills"],
    artifacts: [
      { type: "skill", filename: "google-docs.md", content: `---
name: google-docs
description: How to use Google Docs tools effectively — reading documents with index awareness, surgical text editing, markdown rewrites, formatting, tabs, and comments.
---

# Google Docs

You have full read/write access to Google Docs through the Google Workspace integration. The 25 available tools support surgical index-based editing, full markdown rewrites, formatting, tab management, and comments.

Documents are created via \`drive.create_document\` (not a docs action). All tools that accept \`documentId\` accept either a bare document ID or a full Google Docs URL.

## Available Tools

### List / Search

- **\`docs.list_tabs\`** — List all tabs in a document (tab IDs, titles, nesting).

### Read / Get

- **\`docs.read_document\`** — Read document content. Use \`format=markdown\` for human-readable output or \`format=json\` to get the raw document structure with character indices required for surgical edits.
- **\`docs.list_comments\`** — List all comments on a document (open or resolved).
- **\`docs.get_comment\`** — Get a single comment by ID, including all replies.

### Write / Modify

**Text edits (index-based — requires \`format=json\` read first):**
- **\`docs.insert_text\`** — Insert text at a specific character index.
- **\`docs.append_text\`** — Append plain text at the end of a document (or tab).
- **\`docs.modify_text\`** — Replace text within a start–end index range.
- **\`docs.delete_range\`** — Delete content between a start–end index range.

**Bulk text changes:**
- **\`docs.find_and_replace\`** — Find and replace text throughout the document or a specific tab.

**Markdown-based writes:**
- **\`docs.append_markdown\`** — Convert markdown and append at the end of the document.
- **\`docs.replace_document_with_markdown\`** — Replace the entire document body with rendered markdown content.

**Structural insertion:**
- **\`docs.insert_table\`** — Insert an empty table at a specific index.
- **\`docs.insert_table_with_data\`** — Insert a table pre-populated with data at a specific index.
- **\`docs.insert_image\`** — Insert an image (by URL) at a specific index.
- **\`docs.insert_page_break\`** — Insert a page break at a specific index.
- **\`docs.insert_section_break\`** — Insert a section break (continuous, next page, even page, odd page) at a specific index.

**Tabs:**
- **\`docs.add_tab\`** — Add a new tab to the document.
- **\`docs.rename_tab\`** — Rename an existing tab by tab ID.

**Formatting:**
- **\`docs.apply_text_style\`** — Apply character-level style (bold, italic, underline, font, color, etc.) to a text range.
- **\`docs.apply_paragraph_style\`** — Apply paragraph-level style (heading level, alignment, spacing, etc.) to a range.
- **\`docs.update_section_style\`** — Update section layout properties (margins, columns, etc.).

**Comments:**
- **\`docs.add_comment\`** — Add a new comment anchored to a text range or the whole document.
- **\`docs.reply_to_comment\`** — Reply to an existing comment thread.
- **\`docs.delete_comment\`** — Delete a comment (and its replies).
- **\`docs.resolve_comment\`** — Mark a comment thread as resolved.

## Core Workflows

### Read Then Surgically Edit

Use this when you need to make precise changes without disturbing surrounding content.

\`\`\`
1. docs.read_document({ documentId: "...", format: "json" })
   → Returns raw document structure with character indices

2. Locate the text or range you want to modify in the JSON
   → Note the startIndex and endIndex values

3. Apply targeted edits:
   - docs.modify_text({ documentId: "...", startIndex: 42, endIndex: 67, text: "replacement" })
   - docs.delete_range({ documentId: "...", startIndex: 42, endIndex: 67 })
   - docs.insert_text({ documentId: "...", index: 42, text: "new content" })
\`\`\`

Important: Read with \`format=json\` before any index-based edit. Character indices shift after every mutation, so plan all edits from a single read snapshot and apply them in reverse order (highest index first) to avoid offset drift.

### Find and Replace

For bulk text substitutions — placeholders, renames, or corrections throughout the document:

\`\`\`
docs.find_and_replace({
  documentId: "...",
  find: "{{PROJECT_NAME}}",
  replace: "Wallet Export v2"
})
\`\`\`

Use \`find_and_replace\` for any case where you know the exact text to swap. It is simpler and safer than calculating indices.

### Full Document Rewrite

When you want to replace the entire document body with new markdown content:

\`\`\`
docs.replace_document_with_markdown({
  documentId: "...",
  markdown: "# New Title\\n\\n## Section 1\\n\\nContent here..."
})
\`\`\`

Use this for complete rewrites, template population from scratch, or when structure has changed enough that surgical edits would be more complex than starting fresh.

### Append Content

To add new content at the end without touching existing content:

\`\`\`
# Plain text
docs.append_text({ documentId: "...", text: "New paragraph." })

# Markdown (converted to native formatting)
docs.append_markdown({ documentId: "...", markdown: "## New Section\\n\\nContent..." })
\`\`\`

Use \`append_markdown\` when the content has headings, lists, tables, or other formatting. Use \`append_text\` for simple unformatted additions.

### Working with Tabs

Multi-tab documents require listing tabs first:

\`\`\`
1. docs.list_tabs({ documentId: "..." })
   → Returns tabId, title, nesting for each tab

2. Pass tabId to any index-based tool to scope edits to that tab:
   docs.read_document({ documentId: "...", tabId: "t.abc123", format: "json" })
   docs.insert_text({ documentId: "...", tabId: "t.abc123", index: 10, text: "..." })
\`\`\`

### Commenting

\`\`\`
# Add a comment
docs.add_comment({ documentId: "...", content: "Needs review" })

# Reply to a thread
docs.reply_to_comment({ documentId: "...", commentId: "...", content: "Fixed in v2" })

# Resolve when done
docs.resolve_comment({ documentId: "...", commentId: "..." })
\`\`\`

## Drive Labels Guard Awareness

When the Drive Labels Guard is active (configured per organization), all docs tools that operate on a specific document are subject to label enforcement. The guard classifies each action:

- **\`docs.list_tabs\`** — list/search (label filter applied to results)
- **\`docs.read_document\`, \`docs.list_comments\`, \`docs.get_comment\`** — read/get (document must carry a required label)
- All write/modify tools — require the document to carry a required label before the edit proceeds

If a document does not carry the required label, the tool returns \`"File not found or access denied"\` regardless of actual permissions. This is intentional — it is indistinguishable from a 404 to prevent information leakage.

Documents are created via \`drive.create_document\`, which is classified as a create action. When the guard is active, the newly created document is automatically labeled.

## Tips

- **Index order for multi-edit**: When applying multiple index-based edits from a single read, work from highest index to lowest. Each insertion or deletion shifts indices for everything that follows.
- **Find-and-replace over indices for placeholders**: If the document uses \`{{PLACEHOLDER}}\` style tokens, \`find_and_replace\` is simpler and doesn't require a JSON read.
- **Markdown for new content, JSON for surgery**: Use \`append_markdown\` / \`replace_document_with_markdown\` when generating fresh content. Use \`format=json\` reads + \`modify_text\` / \`delete_range\` when editing existing content at known positions.
- **Tab awareness**: Operations that don't specify a \`tabId\` apply to the first (default) tab. Always call \`list_tabs\` first on documents where you don't know the tab structure.
- **Formatting after content**: Apply \`apply_text_style\` and \`apply_paragraph_style\` after inserting content, targeting the known index range of the newly inserted text.
`, sortOrder: 0 },
      { type: "skill", filename: "google-drive.md", content: `---
name: google-drive
description: How to use Google Drive tools effectively — file discovery, folder navigation, document creation with markdown, file operations, and template workflows.
---

# Google Drive

You have full access to Google Drive through the Google Workspace integration. Drive is the file system layer — use it to find, organize, create, and download files. For editing the content of Google Docs or Sheets, use the \`docs.*\` or \`sheets.*\` tools instead.

## Available Tools

### Discovery (Finding Files)

- **\`drive.list_files\`** — List files with optional folder, MIME type, ownership, and date filtering. Supports sorting and pagination. Use MIME type shortcuts: "document", "spreadsheet", "folder", etc.
- **\`drive.search_files\`** — Full-text search across all file types by name, content, or both. The fastest way to find any file.
- **\`drive.list_documents\`** — List Google Documents only, optionally filtered by name/content.
- **\`drive.search_documents\`** — Search specifically within Google Documents by name, content, or both.
- **\`drive.list_folder_contents\`** — List files and subfolders within a specific folder. Results are sorted with folders first.
- **\`drive.get_document_info\`** — Get metadata for a file: name, type, owner, sharing status, dates, links.
- **\`drive.get_folder_info\`** — Get metadata for a folder including child count.

### File Operations

- **\`drive.create_document\`** — Create a new Google Doc. Optionally provide markdown content that gets converted to formatted Docs content (headings, bold, italic, links, lists, tables).
- **\`drive.create_folder\`** — Create a new folder, optionally inside a parent folder.
- **\`drive.copy_file\`** — Copy a file, optionally to a different folder with a new name.
- **\`drive.move_file\`** — Move a file or folder to a different folder.
- **\`drive.rename_file\`** — Rename a file or folder.
- **\`drive.delete_file\`** — Permanently delete a file (cannot be undone).
- **\`drive.download_file\`** — Download text content of a file. Auto-exports Google Workspace files (Docs to text, Sheets to CSV). Rejects binary files.
- **\`drive.create_from_template\`** — Copy a template document and optionally replace placeholder text (e.g. \`{{name}}\` to \`Alice\`).

## Common Patterns

### Finding Files

Search is the fastest way to find files:

\`\`\`
drive.search_files({ query: "Q1 budget report" })
\`\`\`

Search only by file name:

\`\`\`
drive.search_files({ query: "meeting notes", searchIn: "name" })
\`\`\`

Find only Google Docs:

\`\`\`
drive.list_documents({ query: "project plan" })
\`\`\`

Browse a specific folder:

\`\`\`
drive.list_folder_contents({ folderId: "folder-id-here" })
\`\`\`

List files by type:

\`\`\`
drive.list_files({ mimeType: "spreadsheet" })
\`\`\`

Find recently modified files:

\`\`\`
drive.list_files({ modifiedAfter: "2026-01-01", orderBy: "modifiedTime" })
\`\`\`

### Creating Documents with Markdown

Create a formatted Google Doc from markdown:

\`\`\`
drive.create_document({
  title: "Meeting Notes",
  markdown: "# Meeting Notes\\n\\n## Attendees\\n- Alice\\n- Bob\\n\\n## Action Items\\n1. **Review proposal** by Friday\\n2. Schedule follow-up",
  folderId: "folder-id-here"
})
\`\`\`

The markdown is converted to native Google Docs formatting: headings, bold, italic, links, lists, and more.

### Creating from Templates

Copy a template and fill in placeholders:

\`\`\`
drive.create_from_template({
  templateId: "template-doc-id",
  title: "Offer Letter - Alice",
  folderId: "hr-folder-id",
  replacements: {
    "{{name}}": "Alice Smith",
    "{{title}}": "Senior Engineer",
    "{{start_date}}": "2026-05-01"
  }
})
\`\`\`

### Folder Navigation

Navigate a folder hierarchy:

\`\`\`
drive.get_folder_info({ folderId: "folder-id" })
drive.list_folder_contents({ folderId: "folder-id" })
\`\`\`

### Reading File Content

Download text content:

\`\`\`
drive.download_file({ fileId: "file-id" })
\`\`\`

Google Workspace files are auto-exported: Docs become plain text, Sheets become CSV, Slides become plain text.

### Organizing Files

Move a file:

\`\`\`
drive.move_file({ fileId: "file-id", folderId: "destination-folder-id" })
\`\`\`

Rename a file:

\`\`\`
drive.rename_file({ fileId: "file-id", name: "New Name" })
\`\`\`

Copy a file:

\`\`\`
drive.copy_file({ fileId: "file-id", name: "Copy Name", folderId: "destination-folder-id" })
\`\`\`

## When to Use Drive vs Dedicated Tools

Drive is the file system layer. For editing the **content** of Google Workspace files, use the dedicated tools:

| Task | Use This | NOT This |
|------|----------|----------|
| Create a Google Doc with content | \`drive.create_document\` (markdown) | \`docs.insert_text\` (lower-level) |
| Edit document sections | \`docs.*\` tools | drive tools |
| Read structured doc content | \`docs.read_document\` | \`drive.download_file\` (loses formatting) |
| Read spreadsheet data | \`sheets.read_range\` | \`drive.download_file\` (exports as CSV) |
| Write/format cells | \`sheets.*\` tools | drive tools |
| Find files across Drive | \`drive.search_files\` | \`drive.list_documents\` (Docs only) |
| Get file metadata/links | \`drive.get_document_info\` | docs/sheets tools |
| Move/rename/copy/delete | \`drive.move_file\`, \`drive.rename_file\`, etc. | N/A |

## Google Workspace MIME Types

| Type | MIME Type | Shortcut |
|---|---|---|
| Google Docs | \`application/vnd.google-apps.document\` | \`document\` |
| Google Sheets | \`application/vnd.google-apps.spreadsheet\` | \`spreadsheet\` |
| Google Slides | \`application/vnd.google-apps.presentation\` | \`presentation\` |
| Google Forms | \`application/vnd.google-apps.form\` | \`form\` |
| Folder | \`application/vnd.google-apps.folder\` | \`folder\` |
| PDF | \`application/pdf\` | \`pdf\` |

## Drive Labels Guard

Your organization may have a Drive Labels guard enabled. When active, only files with an admin-configured Google Drive label are accessible.

**If you get "File not found or access denied"** for a file the user says exists, the file likely doesn't have the required Drive label. Tell the user:
- The file needs a specific Google Drive label applied to be accessible to Valet
- They can apply the label in the Google Drive web UI (right-click > Labels)
- Their admin can tell them which label is required

**If search returns fewer results than expected**, the guard may be filtering out unlabeled files. Let the user know that only labeled files are visible.

## Tips

- **Search broadly**: \`search_files\` searches both file names and content. It's the best starting point.
- **Use document-specific search**: \`list_documents\` and \`search_documents\` are faster when you know you need a Google Doc.
- **Browse folders**: \`list_folder_contents\` shows folders first, then files — good for navigation.
- **Binary files are rejected**: \`download_file\` only works with text-based and Google Workspace files.
- **Delete is permanent**: \`delete_file\` cannot be undone. Confirm with the user before deleting.
`, sortOrder: 1 },
      { type: "skill", filename: "google-sheets.md", content: `---
name: google-sheets
description: How to use Google Sheets tools effectively -- 37 actions covering data, sheet management, formatting, tables, charts, conditional formatting, validation, and protection.
---

# Google Sheets

You have full read/write access to Google Sheets through the Google Workspace integration with 37 tools.

## Available Tools

### Reading Data

- **\`sheets.read_spreadsheet\`** -- Read cell values from a range using A1 notation (returns 2D array).
- **\`sheets.get_spreadsheet_info\`** -- Get spreadsheet metadata: title, URL, sheet names, dimensions, sheet IDs. Always start here.
- **\`sheets.list_spreadsheets\`** -- List spreadsheets in Drive, optionally filtered by name.

### Writing Data

- **\`sheets.write_spreadsheet\`** -- Write values to a specific range (overwrites existing data).
- **\`sheets.append_rows\`** -- Append rows after the last row with data. Use for adding entries to tables/logs.
- **\`sheets.batch_write\`** -- Write data to multiple ranges in a single API call (more efficient for bulk updates).
- **\`sheets.clear_range\`** -- Clear values from a range without deleting cells (formatting preserved).
- **\`sheets.create_spreadsheet\`** -- Create a new spreadsheet with a title and optional sheet names.

### Sheet Management

- **\`sheets.add_sheet\`** -- Add a new sheet/tab to an existing spreadsheet.
- **\`sheets.delete_sheet\`** -- Delete a sheet by its numeric ID (use \`get_spreadsheet_info\` to find sheet IDs).
- **\`sheets.rename_sheet\`** -- Rename a sheet/tab.
- **\`sheets.duplicate_sheet\`** -- Duplicate a sheet within a spreadsheet (copies values, formulas, formatting).
- **\`sheets.copy_sheet_to\`** -- Copy a sheet from one spreadsheet to another.

### Cell Formatting

- **\`sheets.format_cells\`** -- Apply formatting to a range: bold, italic, font size, colors, alignment, number format, wrap strategy.
- **\`sheets.read_cell_format\`** -- Read formatting/style of cells (bold, colors, borders, alignment, number format).
- **\`sheets.copy_formatting\`** -- Copy formatting (not values) from a source range to a destination range.
- **\`sheets.set_column_widths\`** -- Set column widths in pixels for one or more columns.
- **\`sheets.set_row_heights\`** -- Set fixed pixel height for row ranges.
- **\`sheets.auto_resize_columns\`** -- Auto-resize columns to fit their content.
- **\`sheets.auto_resize_rows\`** -- Auto-resize rows to fit their content.
- **\`sheets.set_cell_borders\`** -- Set borders on a range (each side independently: top, bottom, left, right, innerHorizontal, innerVertical).
- **\`sheets.freeze_rows_and_columns\`** -- Pin rows/columns so they stay visible when scrolling.

### Tables

- **\`sheets.create_table\`** -- Create a named table with structured columns.
- **\`sheets.get_table\`** -- Get table details (columns, range, properties).
- **\`sheets.list_tables\`** -- List all tables in a spreadsheet.
- **\`sheets.delete_table\`** -- Delete a table (optionally clear data too).
- **\`sheets.update_table_range\`** -- Modify a table's dimensions by updating its range.
- **\`sheets.append_table_rows\`** -- Append rows to a table using table-aware insertion.

### Charts

- **\`sheets.insert_chart\`** -- Insert a chart (BAR, LINE, AREA, COLUMN, SCATTER, COMBO, PIE) with configurable data range and position.
- **\`sheets.delete_chart\`** -- Delete a chart by its chart ID.

### Conditional Formatting

- **\`sheets.add_conditional_formatting\`** -- Add a conditional formatting rule (NUMBER_GREATER, TEXT_CONTAINS, CUSTOM_FORMULA, BLANK, NOT_BLANK, etc.).
- **\`sheets.delete_conditional_formatting\`** -- Delete a conditional formatting rule by index.
- **\`sheets.get_conditional_formatting\`** -- List all conditional formatting rules for a sheet.

### Data Validation

- **\`sheets.set_dropdown_validation\`** -- Add or remove dropdown lists on a range. Omit values to clear.

### Protection

- **\`sheets.protect_range\`** -- Lock a range or entire sheet to prevent accidental edits. Supports warning-only mode.

### Row Grouping

- **\`sheets.group_rows\`** -- Create collapsible row groups.
- **\`sheets.ungroup_all_rows\`** -- Remove all row groupings from a sheet.

## A1 Notation

All range parameters use A1 notation:

| Notation | Meaning |
|---|---|
| \`Sheet1!A1:C10\` | Cells A1 through C10 on Sheet1 |
| \`Sheet1!A:C\` | Entire columns A through C |
| \`Sheet1!1:5\` | Entire rows 1 through 5 |
| \`A1:C10\` | Range on the first sheet (omitting sheet name) |
| \`Sheet1!A1\` | Single cell |
| \`'Sheet Name With Spaces'!A1:B2\` | Quote sheet names with spaces |

## Common Patterns

### Understand Before Modifying

Always check the spreadsheet structure first:

\`\`\`
1. sheets.get_spreadsheet_info({ spreadsheetId: "..." })
2. sheets.read_spreadsheet({ spreadsheetId: "...", range: "Sheet1!A1:Z1" })  // headers
3. sheets.read_spreadsheet({ spreadsheetId: "...", range: "Sheet1!A1:Z10" }) // sample data
4. sheets.write_spreadsheet({ ... })  // now write with confidence
\`\`\`

### Appending Data

Use \`append_rows\` to add rows to the end of a table:

\`\`\`
sheets.append_rows({
  spreadsheetId: "...",
  range: "Sheet1!A:D",
  data: [
    ["2026-03-15", "New item", 42, "active"],
    ["2026-03-15", "Another item", 17, "pending"]
  ]
})
\`\`\`

### Batch Writing

When updating multiple ranges, use \`batch_write\` for efficiency:

\`\`\`
sheets.batch_write({
  spreadsheetId: "...",
  data: [
    { range: "Sheet1!A1:B1", values: [["Header1", "Header2"]] },
    { range: "Sheet2!A1:A3", values: [["X"], ["Y"], ["Z"]] }
  ]
})
\`\`\`

### Working with Tables

Tables provide structured data with named columns. Use tables for data that needs column-level operations:

\`\`\`
1. sheets.create_table({ spreadsheetId: "...", name: "Sales", range: "Sheet1!A1:D10", columns: ["Date", "Product", "Qty", "Total"] })
2. sheets.append_table_rows({ spreadsheetId: "...", tableId: "...", values: [["2026-04-01", "Widget", 5, 25.00]] })
3. sheets.list_tables({ spreadsheetId: "..." })  // see all tables
\`\`\`

### Formatting

Apply formatting after writing data:

\`\`\`
sheets.format_cells({
  spreadsheetId: "...",
  range: "Sheet1!A1:D1",
  format: {
    backgroundColor: { red: 0.2, green: 0.2, blue: 0.2 },
    textFormat: { bold: true, foregroundColor: { red: 1, green: 1, blue: 1 }, fontSize: 11 },
    horizontalAlignment: "LEFT"
  }
})
\`\`\`

Read existing formatting to match styles:

\`\`\`
sheets.read_cell_format({ spreadsheetId: "...", range: "Sheet1!A5:F5" })
\`\`\`

Copy formatting from one range to another:

\`\`\`
sheets.copy_formatting({
  spreadsheetId: "...",
  sourceRange: "Sheet1!A1:D1",
  destinationRange: "Sheet1!A10:D10"
})
\`\`\`

### Charts

Insert a chart from data:

\`\`\`
sheets.insert_chart({
  spreadsheetId: "...",
  chartType: "BAR",
  sourceRange: "Sheet1!A1:C10",
  title: "Sales by Region"
})
\`\`\`

### Conditional Formatting

Highlight cells meeting conditions:

\`\`\`
sheets.add_conditional_formatting({
  spreadsheetId: "...",
  range: "Sheet1!C2:C100",
  conditionType: "NUMBER_GREATER",
  conditionValues: ["100"],
  format: { backgroundColor: { red: 0.85, green: 0.95, blue: 0.85 } }
})
\`\`\`

Use \`CUSTOM_FORMULA\` for complex conditions:

\`\`\`
sheets.add_conditional_formatting({
  spreadsheetId: "...",
  range: "Sheet1!A2:D100",
  conditionType: "CUSTOM_FORMULA",
  conditionValues: ["=$D2>1000"],
  format: { textFormat: { bold: true } }
})
\`\`\`

### Dropdown Validation

Create dropdown lists:

\`\`\`
sheets.set_dropdown_validation({
  spreadsheetId: "...",
  range: "Sheet1!B2:B100",
  values: ["Open", "In Progress", "Done"],
  strict: true,
  inputMessage: "Select a status"
})
\`\`\`

### Protection

Lock header rows:

\`\`\`
sheets.protect_range({
  spreadsheetId: "...",
  range: "Sheet1!1:1",
  description: "Header row - do not edit",
  warningOnly: false
})
\`\`\`

## Tips

- **Check structure first**: Always call \`get_spreadsheet_info\` before writing.
- **Append vs Write**: Use \`append_rows\` to add to the end. Use \`write_spreadsheet\` to overwrite a specific location.
- **Sheet IDs vs Names**: Most tools use sheet names in A1 notation. \`delete_sheet\`, \`rename_sheet\`, \`duplicate_sheet\` use numeric sheet IDs (from \`get_spreadsheet_info\`).
- **Empty cells**: Empty cells appear as \`""\`. When writing, use \`""\` or \`null\`.
- **Border styles**: SOLID, SOLID_MEDIUM, SOLID_THICK, DASHED, DOTTED, DOUBLE, NONE.
- **Colors**: RGB floats from 0 to 1. Black = \`{red:0, green:0, blue:0}\`, White = \`{red:1, green:1, blue:1}\`.
- **Hex colors in borders**: \`set_cell_borders\` accepts hex strings like \`"#FF0000"\` for color.
`, sortOrder: 2 },
    ],
  },
  {
    name: "linear",
    version: "0.0.1",
    description: "Linear integration for issue tracking and project management",
    icon: "🎯",
    actionType: "mcp",
    capabilities: ["actions"],
    artifacts: [],
  },
  {
    name: "memory-compaction",
    version: "0.0.1",
    description: "Memory compaction plugin for OpenCode",
    icon: "🧠",
    capabilities: ["tools"],
    artifacts: [
      { type: "tool", filename: "memory-compaction.ts", content: `export default async () => {
  return {
    "experimental.session.compacting": async (_input: unknown, output: { context: string[] }) => {
      output.context.push(\`
COMPACTION INSTRUCTIONS — follow exactly before writing your summary:

Your summary must contain these sections. Do NOT omit any of them.
Anything not captured here is permanently lost after compaction.

## Active Work
- Task(s) currently in progress (what, status, what's blocking)
- Child session IDs and their last known status
- What the user is waiting for (if anything)

## Key Decisions Made
- Architectural, process, or preference decisions from this session
- Any constraints or bugs discovered

## Artifacts Created
- Branches, PRs, commits, files changed (include identifiers like PR #N, branch name, commit SHA)

## Things to Remember
- Repo URLs learned this session
- User preferences stated this session
- Project facts discovered (stack, conventions, etc.)

## Resume Instructions
When you resume after this compaction, your FIRST action must be:
1. Call mem_patch to write a journal entry summarizing the above:
   mem_patch("journal/YYYY-MM-DD.md", [{ op: "append", content: "\\\\n\\\\n## [time] — Resumed after compaction\\\\n[paste Active Work + Artifacts here]" }])
2. Check on any child sessions that were running (use get_session_status)
3. Then continue whatever was in progress

Do not respond to the user before completing step 1.
\`);
    },
  };
};
`, sortOrder: 0 },
    ],
  },
  {
    name: "notion",
    version: "0.0.1",
    description: "Notion integration for pages, databases, and workspaces",
    icon: "📝",
    actionType: "mcp",
    capabilities: ["actions"],
    artifacts: [],
  },
  {
    name: "personas",
    version: "0.0.1",
    description: "Agent persona and skill management",
    icon: "🎭",
    capabilities: ["skills"],
    artifacts: [
      { type: "skill", filename: "personas.md", content: `---
name: personas
description: Create and configure agent personas with attached skills. Manage the skill library and understand skill sources.
---

# Persona & Skill Management

## Concepts

### Skills

Skills are markdown documents that teach agents how to perform specific tasks. Every skill has a **source** that determines where it came from and whether you can edit it:

| Source | What it is | Editable? | Example |
|--------|-----------|-----------|---------|
| \`builtin\` | Platform-shipped skills | No | browser, workflows |
| \`plugin\` | Skills from installed extensions | No | custom org plugins |
| \`managed\` | Skills created by users or agents | Yes (owner only) | "deploy-checklist", "code-review-frontend" |

Skills also have **visibility**:
- \`private\` — only the creator can see and use it
- \`shared\` — visible to the entire org

### Personas

Personas are instruction sets that customize agent behavior. A persona has:
- **Name and icon** — human-readable identity
- **Instructions** — system prompt markdown that defines the agent's role and behavior
- **Attached skills** — skills that auto-load when a session starts with this persona

### How skills reach an agent session

When a session starts, the system loads skills in this order:
1. If the session has a **persona** → load skills attached to that persona
2. If no persona → load **org default skills**
3. Agent can always **search and read** additional skills on demand from the full library

This means attaching a skill to a persona guarantees it's in the agent's context from the first message — no searching needed.

## Common Workflows

### Creating a specialized agent

1. **Create skills** for the agent's domain knowledge:
   \`\`\`
   create_skill(name: "Frontend Code Review", content: "# Frontend Review Standards\\n\\n...")
   \`\`\`

2. **Create a persona** with role instructions:
   \`\`\`
   create_persona(name: "Frontend Reviewer", icon: "🔍", instructions: "You are a frontend code reviewer...")
   \`\`\`

3. **Attach skills** to the persona:
   \`\`\`
   attach_skill_to_persona(personaId: "<persona-id>", skillId: "<skill-id>")
   \`\`\`

4. **Spawn a session** with the persona (from orchestrator):
   \`\`\`
   spawn_session(task: "Review PR #42", persona_id: "<persona-id>", ...)
   \`\`\`

### Inspecting a persona's configuration

\`\`\`
list_persona_skills(personaId: "<persona-id>")
\`\`\`

Returns all attached skills with their source, description, and sort order.

### Reusing existing skills

Before creating a new skill, search the library:
\`\`\`
search_skills(query: "code review")
\`\`\`

You can attach builtin or plugin skills to personas — they don't need to be managed. Any skill from any source can be attached.

### Updating a persona's skill set

- **Add a skill:** \`attach_skill_to_persona(personaId, skillId)\`
- **Remove a skill:** \`detach_skill_from_persona(personaId, skillId)\`
- **Reorder:** Re-attach with a different \`sortOrder\` — attaching an already-attached skill updates its sort order (lower = loaded first)

## Tool Reference

| Tool | Purpose |
|------|---------|
| \`create_persona\` | Create a new persona with name, icon, instructions |
| \`update_persona\` | Update persona metadata or instructions |
| \`delete_persona\` | Remove a persona |
| \`list_personas\` | List all available personas |
| \`create_skill\` | Create a managed skill |
| \`update_skill\` | Update a managed skill's content |
| \`delete_skill\` | Delete a managed skill |
| \`search_skills\` | Search the skill library by keyword |
| \`read_skill\` | Read a skill's full content |
| \`attach_skill_to_persona\` | Attach a skill to a persona |
| \`detach_skill_from_persona\` | Detach a skill from a persona |
| \`list_persona_skills\` | List skills attached to a persona |

## Tips

- **Visibility defaults differ:** Skills default to \`private\`, personas default to \`shared\`. Set visibility explicitly when creating.
- **Sort order matters:** Skills load in sort order. Put foundational skills (coding standards, conventions) at lower sort orders so they appear first in context.
- **Managed skills only:** You can only edit/delete skills with \`source: managed\`. Builtin and plugin skills are read-only, but you can still attach them to personas.
- **Skill content format:** Use YAML frontmatter for metadata (tags, version) followed by markdown content. The content is what gets loaded into the agent's context.
`, sortOrder: 0 },
    ],
  },
  {
    name: "sandbox-tunnels",
    version: "0.0.1",
    description: "Sandbox tunnel management",
    icon: "🔗",
    capabilities: ["skills"],
    artifacts: [
      { type: "skill", filename: "sandbox-tunnels.md", content: `---
name: sandbox-tunnels
description: Expose sandboxed services via public Cloudflare Quick Tunnels. Each tunnel gets a unique hostname with no path prefix — apps work as if hosted at root.
---

# Sandbox Tunnels

## Goal
Expose sandboxed services through public Cloudflare Quick Tunnels. Each tunnel gets its own unique \`*.trycloudflare.com\` hostname — no path prefix, no base URL configuration needed.

## Quick Path
1. Start services bound to \`0.0.0.0\` inside the sandbox.
2. Register tunnels via \`register_tunnel\`.
3. Use the returned public URL directly — no CORS, no base path.

## Tunnel Workflow
1. Start backend:
   - Example: \`python backend.py --host 0.0.0.0 --port 3000\`
2. Start frontend:
   - Example: \`pnpm dev --host 0.0.0.0 --port 3001\`
3. Register tunnels:
   - \`register_tunnel { name: "api", port: 3000 }\`
   - \`register_tunnel { name: "frontend", port: 3001 }\`
4. Each tunnel returns a unique public URL like \`https://random-words.trycloudflare.com\`
5. Share the URL — no token or auth needed for public access.

## Key Differences from Gateway Tunnels
- **No path prefix**: Apps are served at \`/\`, not \`/t/<name>/\`.
- **No base path config**: No need to set \`base\`, \`basePath\`, \`PUBLIC_URL\`, or \`assetPrefix\`.
- **No JWT/token**: Cloudflare Quick Tunnels are publicly accessible (no gateway auth).
- **Independent hostnames**: Each tunnel is a separate origin — no CORS between tunnels.

## Cross-Origin Between Tunnels
Since each tunnel is its own origin, frontend-to-backend calls are cross-origin. Options:
- **Enable CORS** on the backend (recommended for APIs).
- **Proxy through the frontend** (e.g., Vite proxy, Next.js rewrites).
- **Use the gateway fallback**: The old \`/t/<name>\` paths still work through the gateway for same-origin access.

## Frontend Integration
\`\`\`js
// Use the tunnel URL directly
const API_URL = "https://backend-words.trycloudflare.com"
fetch(\`\${API_URL}/health\`)

// Or set via environment variable
// API_URL=https://backend-words.trycloudflare.com
\`\`\`

## WebSocket Support
Cloudflare Quick Tunnels support WebSockets natively:
\`\`\`js
const ws = new WebSocket("wss://backend-words.trycloudflare.com/ws")
\`\`\`

## Debugging Checklist
- \`ss -tlnp | rg <port>\`: confirm service is listening on 0.0.0.0.
- \`curl -sS http://127.0.0.1:<port>/health\`: confirm service responds locally.
- If tunnel URL returns 502, the local service isn't reachable on that port.
- \`list_tunnels\` to see all active tunnels and their URLs.

## Deleting Tunnels
- \`unregister_tunnel { name: "api" }\` kills the cloudflared process.
- Users can also delete tunnels from the session UI.

## Gateway Fallback
The gateway \`/t/<name>\` paths still work for same-origin access within the sandbox. These require JWT auth and are useful for internal service-to-service calls.

## API Access
- \`GET /api/sessions/:id/tunnels\` → \`{ gatewayUrl, tunnels }\` (tunnels include cloudflared URLs)
`, sortOrder: 0 },
    ],
  },
  {
    name: "sentry",
    version: "0.0.1",
    description: "Sentry integration for error tracking and monitoring",
    icon: "🐛",
    actionType: "mcp",
    capabilities: ["actions"],
    artifacts: [],
  },
  {
    name: "slack",
    version: "0.0.1",
    description: "Slack integration for actions (messages, channels, users) and channel transport",
    icon: "💬",
    capabilities: ["actions","channels"],
    artifacts: [],
  },
  {
    name: "stripe",
    version: "0.0.1",
    description: "Stripe integration for payments, customers, and subscriptions",
    icon: "💳",
    actionType: "mcp",
    capabilities: ["actions"],
    artifacts: [],
  },
  {
    name: "telegram",
    version: "0.0.1",
    description: "Telegram bot messaging and transport",
    icon: "📱",
    capabilities: ["channels"],
    artifacts: [],
  },
  {
    name: "typefully",
    version: "0.0.1",
    description: "Typefully integration for social media content management",
    icon: "📝",
    actionType: "mcp",
    capabilities: ["actions"],
    artifacts: [],
  },
  {
    name: "workflows",
    version: "0.0.1",
    description: "Workflow lifecycle and operations",
    icon: "🔄",
    capabilities: ["skills"],
    artifacts: [
      { type: "skill", filename: "workflows.md", content: `---
name: workflows
description: End-to-end Valet workflow operations. Use when creating, updating, deleting, running, scheduling, debugging, rolling back, or self-modifying workflows; when managing workflow executions and approvals; when configuring trigger behavior; when passing repository context into workflow runs; and when using agent_message workflow steps.
---

# Workflows

## Use the workflow tools, not raw API calls

Use these tools for lifecycle operations:

- \`list_workflows\`, \`get_workflow\`, \`sync_workflow\`, \`update_workflow\`, \`delete_workflow\`
- \`list_workflow_history\`, \`rollback_workflow\`
- \`list_workflow_proposals\`, \`create_workflow_proposal\`, \`review_workflow_proposal\`, \`apply_workflow_proposal\`
- \`run_workflow\`, \`list_workflow_executions\`, \`get_execution\`, \`get_execution_steps\`, \`debug_execution\`, \`approve_execution\`, \`cancel_execution\`
- \`list_triggers\`, \`sync_trigger\`, \`run_trigger\`, \`delete_trigger\`

## Think in 4 layers

1. Workflow definition: versioned JSON with non-empty \`steps\`.
2. Trigger configuration: dispatch rules for \`manual\`, \`webhook\`, or \`schedule\`.
3. Execution record: immutable run state, status, step traces, and approval token lifecycle.
4. Workflow session: dedicated sandbox session (\`purpose: workflow\`) started/woken by the workflow executor.

## Choose the right lifecycle tool

- Use \`sync_workflow\` for create or full-definition upsert.
- Use \`update_workflow\` for partial metadata/definition patch (\`name\`, \`description\`, \`slug\`, \`version\`, \`enabled\`, \`tags\`, \`data\`).
- Use \`delete_workflow\` to remove workflows (and linked triggers).
- Use \`list_workflow_history\` before rollback or forensic comparison.
- Use \`rollback_workflow\` with a \`target_workflow_hash\` from history.

## Use proposal flow for self-modifying workflows

Follow this sequence:

1. Use \`get_workflow\` and compute/use current workflow hash as \`base_workflow_hash\`.
2. Use \`create_workflow_proposal\`.
3. Use \`review_workflow_proposal\` (\`approve=true/false\`).
4. Use \`apply_workflow_proposal\` after approval.

Notes:

- Proposal creation enforces base-hash matching.
- Workflow must allow self-modification (\`constraints.allowSelfModification === true\`).
- Use \`list_workflow_proposals\` to inspect status transitions (\`pending\`, \`approved\`, \`rejected\`, \`applied\`, \`failed\`).

## Run and operate executions

Run:

- Use \`run_workflow\` with \`workflow_id\`.
- Optionally pass \`variables_json\`.
- Optionally pass repo context: \`repo_url\`, \`repo_branch\`, \`repo_ref\`, \`source_repo_full_name\`.

Inspect:

- Use \`list_workflow_executions\` for recent runs.
- Use \`get_execution\` for authoritative status and current \`resumeToken\`.
- Use \`get_execution_steps\` for ordered normalized step traces.
- Use \`debug_execution\` first when a run stalls/fails.

Approval/cancel:

- Use \`approve_execution\` with the latest \`resume_token\` from \`get_execution\`.
- Use \`cancel_execution\` for stuck/inconsistent runs.

## Configure triggers and scheduling

Use \`sync_trigger\` for create/update:

- \`type=manual\`
- \`type=webhook\` requires \`webhook_path\` (optional method/secret)
- \`type=schedule\` requires \`schedule_cron\`

Schedule specifics:

- \`schedule_cron\` must be a 5-field cron expression.
- \`schedule_timezone\` uses IANA TZ names.
- \`schedule_target=workflow\` (default): dispatches workflow execution.
- \`schedule_target=orchestrator\`: dispatches \`schedule_prompt\` to orchestrator session.
- \`schedule_prompt\` is required when \`schedule_target=orchestrator\`.

Use \`run_trigger\` to test behavior immediately.

Use \`delete_trigger\` to remove stale triggers.

Variable mapping note:

- Keep \`variable_mapping_json\` paths simple (\`$.field\`), since extraction is shallow.

## Understand workflow execution context

Workflow runs do not execute in the orchestrator sandbox.

Execution context behavior:

1. A workflow session is created as a dedicated session (\`purpose: workflow\`) and initially hibernated.
2. \`WorkflowExecutorDO\` wakes/boots that workflow sandbox when enqueue/resume happens.
3. The executor dispatches a workflow-run prompt into that workflow session.

Repository context behavior:

- Repo context is stored in \`session_git_state\` for the workflow session.
- Executor injects \`REPO_URL\`, \`REPO_BRANCH\`, \`REPO_REF\` env vars into the sandbox.
- Sandbox startup clones \`REPO_URL\` into \`/workspace/<repo>\`, checks out branch/ref when provided, and sets working directory to the clone.

## Author workflow definitions with current runtime behavior

Minimum requirement:

- \`workflow.steps\` must be a non-empty array.
- Each step must have \`id\` (string), \`name\` (string), and \`type\` (string).

Valid step types: \`bash\`, \`tool\`, \`approval\`, \`conditional\`, \`parallel\`, \`agent\`, \`agent_message\`.

### \`bash\` step (preferred for shell commands)

Use \`type: "bash"\` for shell commands. This is a first-class step type.

Required fields:
- \`command\` (string): The shell command to execute.

Optional fields:
- \`description\` (string): Human-readable description of what this command does.
- \`cwd\` (string): Working directory.
- \`timeoutMs\` (number): Timeout in milliseconds (default 120000, max 600000).
- \`outputVariable\` (string): Variable name to store command output.

Example:
\`\`\`json
{
  "id": "1",
  "name": "Run tests",
  "type": "bash",
  "command": "npm test",
  "description": "Run the test suite"
}
\`\`\`

**Do NOT use \`type: "tool"\` with \`tool: "bash"\` for shell commands.** Use \`type: "bash"\` instead.

### \`tool\` step

For non-bash tools only. Requires \`tool\` (string) and optionally \`arguments\` (object).

### \`approval\` step

Pauses execution and waits for human approval.

Optional fields:
- \`prompt\` (string): Message shown to the approver.

### \`conditional\` step

Evaluates a condition and runs \`then\` or \`else\` branch.

Required fields:
- \`condition\`: Boolean value, or object like \`{ "variable": "varName", "equals": "value" }\`.

Optional fields:
- \`then\` (array of steps): Steps to run when condition is true.
- \`else\` (array of steps): Steps to run when condition is false.

### \`parallel\` step

Runs nested steps. Requires \`steps\` (array of steps).

### \`agent\` step

Dispatches work to an AI agent.

Optional fields:
- \`goal\` (string): What the agent should accomplish.
- \`context\` (string): Additional context for the agent.

### \`agent_message\` step

Sends a message to the workflow session agent.

Required: Provide message via \`content\` (preferred), or \`message\`, or \`goal\`.

Optional fields:
- \`interrupt\` (boolean).
- \`await_response\` (or \`awaitResponse\`) boolean.
- \`await_timeout_ms\` (or \`awaitTimeoutMs\`) number, minimum 1000.

Behavior:
- Non-await mode sends a message to the current workflow session agent.
- Await mode runs a temporary OpenCode session and returns response text in step output.

### Complete workflow example

\`\`\`json
{
  "steps": [
    {
      "id": "1",
      "name": "Install dependencies",
      "type": "bash",
      "command": "npm install",
      "description": "Install project dependencies"
    },
    {
      "id": "2",
      "name": "Run linter",
      "type": "bash",
      "command": "npm run lint",
      "description": "Check code quality"
    },
    {
      "id": "3",
      "name": "Run tests",
      "type": "bash",
      "command": "npm test",
      "outputVariable": "test_results"
    },
    {
      "id": "4",
      "name": "Approve deployment",
      "type": "approval",
      "prompt": "Tests passed. Deploy to production?"
    },
    {
      "id": "5",
      "name": "Deploy",
      "type": "bash",
      "command": "npm run deploy"
    }
  ]
}
\`\`\`

## Reliable operating playbook

1. Use \`list_workflows\` and \`list_triggers\` before creating/updating to avoid duplicates.
2. Use \`get_workflow\` before patching critical definitions.
3. Use \`run_workflow\` or \`run_trigger\` for tests.
4. Use \`debug_execution\` first for incidents.
5. Use fresh \`resume_token\` from \`get_execution\` before \`approve_execution\`.
6. Use \`cancel_execution\` when state is inconsistent, then rerun cleanly.
7. Use \`list_workflow_history\` and \`rollback_workflow\` for safe recovery.
`, sortOrder: 0 },
    ],
  },
];
