/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as SessionsIndexRouteImport } from './routes/sessions/index'
import { Route as IntegrationsIndexRouteImport } from './routes/integrations/index'
import { Route as SessionsSessionIdRouteImport } from './routes/sessions/$sessionId'
import { Route as IntegrationsCallbackRouteImport } from './routes/integrations/callback'
import { Route as SessionsSessionIdFilesRouteImport } from './routes/sessions/$sessionId/files'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsIndexRoute = SessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsIndexRoute = IntegrationsIndexRouteImport.update({
  id: '/integrations/',
  path: '/integrations/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsSessionIdRoute = SessionsSessionIdRouteImport.update({
  id: '/sessions/$sessionId',
  path: '/sessions/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsCallbackRoute = IntegrationsCallbackRouteImport.update({
  id: '/integrations/callback',
  path: '/integrations/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsSessionIdFilesRoute = SessionsSessionIdFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => SessionsSessionIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/integrations/callback': typeof IntegrationsCallbackRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRouteWithChildren
  '/integrations/': typeof IntegrationsIndexRoute
  '/sessions/': typeof SessionsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/sessions/$sessionId/files': typeof SessionsSessionIdFilesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/integrations/callback': typeof IntegrationsCallbackRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRouteWithChildren
  '/integrations': typeof IntegrationsIndexRoute
  '/sessions': typeof SessionsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/sessions/$sessionId/files': typeof SessionsSessionIdFilesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/integrations/callback': typeof IntegrationsCallbackRoute
  '/sessions/$sessionId': typeof SessionsSessionIdRouteWithChildren
  '/integrations/': typeof IntegrationsIndexRoute
  '/sessions/': typeof SessionsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/sessions/$sessionId/files': typeof SessionsSessionIdFilesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/integrations/callback'
    | '/sessions/$sessionId'
    | '/integrations/'
    | '/sessions/'
    | '/settings/'
    | '/sessions/$sessionId/files'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/integrations/callback'
    | '/sessions/$sessionId'
    | '/integrations'
    | '/sessions'
    | '/settings'
    | '/sessions/$sessionId/files'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/integrations/callback'
    | '/sessions/$sessionId'
    | '/integrations/'
    | '/sessions/'
    | '/settings/'
    | '/sessions/$sessionId/files'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  IntegrationsCallbackRoute: typeof IntegrationsCallbackRoute
  SessionsSessionIdRoute: typeof SessionsSessionIdRouteWithChildren
  IntegrationsIndexRoute: typeof IntegrationsIndexRoute
  SessionsIndexRoute: typeof SessionsIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/': {
      id: '/sessions/'
      path: '/sessions'
      fullPath: '/sessions/'
      preLoaderRoute: typeof SessionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations/': {
      id: '/integrations/'
      path: '/integrations'
      fullPath: '/integrations/'
      preLoaderRoute: typeof IntegrationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$sessionId': {
      id: '/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof SessionsSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations/callback': {
      id: '/integrations/callback'
      path: '/integrations/callback'
      fullPath: '/integrations/callback'
      preLoaderRoute: typeof IntegrationsCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions/$sessionId/files': {
      id: '/sessions/$sessionId/files'
      path: '/files'
      fullPath: '/sessions/$sessionId/files'
      preLoaderRoute: typeof SessionsSessionIdFilesRouteImport
      parentRoute: typeof SessionsSessionIdRoute
    }
  }
}

interface SessionsSessionIdRouteChildren {
  SessionsSessionIdFilesRoute: typeof SessionsSessionIdFilesRoute
}

const SessionsSessionIdRouteChildren: SessionsSessionIdRouteChildren = {
  SessionsSessionIdFilesRoute: SessionsSessionIdFilesRoute,
}

const SessionsSessionIdRouteWithChildren =
  SessionsSessionIdRoute._addFileChildren(SessionsSessionIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  IntegrationsCallbackRoute: IntegrationsCallbackRoute,
  SessionsSessionIdRoute: SessionsSessionIdRouteWithChildren,
  IntegrationsIndexRoute: IntegrationsIndexRoute,
  SessionsIndexRoute: SessionsIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
