export type {
  IntegrationService,
  Integration,
  IntegrationConfig,
  SyncResult,
  SyncError,
  SessionStatus,
  AgentSession,
  Message,
  ToolCall,
  User,
  CreateSessionRequest,
  CreateSessionResponse,
  SendMessageRequest,
  Attachment,
  ListSessionsResponse,
  ConfigureIntegrationRequest,
  TriggerSyncRequest,
  SyncStatusResponse,
  StoredAPIKey,
  WebhookPayload,
  DashboardStatsResponse,
  DashboardHeroStats,
  DashboardDelta,
  DashboardDayActivity,
  DashboardTopRepo,
  DashboardRecentSession,
  DashboardActiveSession,
} from '@agent-ops/shared';

export type { GitHub, Gmail, GoogleCalendar } from '@agent-ops/shared';
