// AUTO-GENERATED by scripts/generate-plugin-registry.ts — do not edit

import type { RepoProvider } from '@valet/sdk/repos';
import { githubRepoProvider as rp0 } from '@valet/plugin-github/repo';

export const installedRepoProviders: RepoProvider[] = [rp0];
